[project]
name = "blockhouse-api"
version = "0.1.0"
description = "Blockhouse API as per work trial assignment."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "sqlmodel>=0.0.22",
    "uvicorn>=0.34.0",
]
